### ISSUE TITLE
I CAN'T COMPILE

### ISSUE THREAD

**Issue by Github3010** [n64decomp/sdk-tools#3]
I can't compile sdk-tools on Windows because it only compiles on Unix. Could you convert the compilation from Unix to Windows and send an EXE file?

**Comment by gdandsm64fan123** [comment]
random comment

**Comment by BridgeHeadland** [comment]
The bad thing about the n64decomp repositories is that few of them have issues on the menu bar (if I can call it that), and as far as I can see none of them have discussions. They should all have that, I think, then it will be easier to give input, inform if something is not as it should be, and come up with ideas. For example, I have noticed that if I mod the PAL version of Banjo-Kazooie, the modded z64 file will not work.
One idea I'd like to come up with is an online Javascript rewrite of N64Decomp. The idea is inspired by the fact that the C++-based version of the game modding program Camoto - Camoto Desktop was replaced with Camoto Online, which is based on Javascript, due to the fact that the group of people who are interested in modding games and such, and who are also familiar with C++ is vanishingly small, and that very few game enthusiasts will be able to contribute to this code base, despite the interest being quite large. I don't think the current N64Decomp should be replaced, it could be possible to use both of them as well.
You can go to the Camoto link -http://www.shikadi.net/camoto/desktop/

**Comment by gdandsm64fan123** [comment]
hey uhhh maybe use wsl?

**Comment by BridgeHeadland** [comment]
@gdandsm64fan123 This issue is indeed related to sdk-tools, and indeed I mentioned modding Banjo-Kazooie here, it's because I can't find issues and discussions in the right places. I've had the same experience with Perfect Dark as with Banjo-Kazooie, that the modded z64 file doesn't show up if I trying to mod PAL versions of the Nintendo 64 games. I believe that it is not possible to mod PAL versions of Nintendo 64 games in Github as of today, at least not with WSL, and one might experience the same obstacle trying to mod Japanese versions of the Nintendo 64 games, I din’t know. I've noticed that whenever I mention modding PAL versions anywhere, everyone goes silent like oysters 4 any reasons, meaning it's impossible to figure out if there's a secret way to mod PAL versions, or whether it will be fixed eventually.
